### Get All Data
GET http://localhost:3000/api/categories
Accept: application/json

### Create New Category
POST http://localhost:3000/api/categories
Accept: application/json
Content-Type: application/json

{
    "name" : ""
}

### Get Category By id
GET http://localhost:3000/api/categories/6
Accept: application/json

### Update Category by Id
PUT http://localhost:3000/api/categories/6
Accept: application/json
Content-Type: application/json

{
  "name" : "tabsul"
}

### DELETE Category by Id
DELETE http://localhost:3000/api/categories/6
Accept: application/json